# Generated by Django 4.2.29 on 2026-03-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_paymentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='split_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
